batch_size: 64
num_workers: 20
epochs: 50
device: "cuda:1"
lr: 0.0005
tqdm_log: True
ckpt_freq: 1500
debug: True

im_size: 64
# model
nz: 256
ngf: 512
action_type: "amw"
loss_type: "simple"
affine_latent: False
ident_preserving: True

use_wandb: True

dataset_path: "/home/simo/dl/global_dataset/celeba/img_align_celeba/img_align_celeba"