batch_size: 64
num_workers: 20
epochs: 50
device: "cuda:1"
lr: 0.0005
tqdm_log: True
ckpt_freq: 1500
debug: True

im_size: 64
# model
nz: 128
ngf: 256
action_type: "amw"
loss_type: "compat"
affine_latent: False
ident_preserving: True

use_wandb: True

dataset_path: "./data/euc_2_circle_dataset"
